name: Build Game

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rid: [win-x64, linux-x64, osx-x64]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - run: dotnet publish ./src/MyGame/MyGame.csproj -c Release -r ${{ matrix.rid }} --self-contained true /p:PublishSingleFile=true

      - uses: actions/upload-artifact@v4
        with:
          name: game-${{ matrix.rid }}
          path: src/MyGame/bin/Release/net10.0/${{ matrix.rid }}/publish/*
